error: do not dereference and borrow NetavarkError
There is no need to dereference and borrow , infact this is considered
bad by clippy.

https://rust-lang.github.io/rust-clippy/master/index.html#borrow_deref_ref

Signed-off-by: Aditya R <arajan@redhat.com>