error: remove unused equal code
This code is not required. To check for a specific error we should match
the type instead.

Signed-off-by: Paul Holzinger <pholzing@redhat.com>