error: NetavarkError use Into<String> Trait
Instead of using two function for types String and str we can just use
a generic which implements Into<String>. This allows us to only use one
function for both.

Signed-off-by: Paul Holzinger <pholzing@redhat.com>